adding hpa and metrics-server
failling to spin up mertrics-server due to
Error: error creating self-signed certificates: mkdir apiserver.local.config: permission denied